# version: '3.8'

# services:
#   nginx:
#     build:
#       context: ./docker/nginx
#     ports:
#       - "80:80"
#       - "443:443"
#     volumes:
#       - ./:/var/www
#       - ./docker/nginx/nginx_log:/var/log/nginx
#       - ./docker/php/php-fpm/php-fpm.log:/var/log/php-fpm.log
#       - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/nginx.conf
#     depends_on:
#       - php
#     networks:
#       - app-network

#   php:
#     build:
#       context: ./docker/php
#     ports:
#       - "8001:80"    
#     environment:
#       - DB_PORT=3306
#       - DB_HOST=mysql
#       # - DB_HOST=host.docker.internal
#     volumes:
#       - ./:/var/www/html
#     depends_on:
#       - mysql
#     networks:
#       - app-network

#   mysql:
#     build:
#       context: ./docker/mysql
#     ports:
#       - "5554:3306"
#     volumes:
#       - db_data:/var/lib/mysql
#     environment:
#       - MYSQL_DATABASE=social_media
#       - MYSQL_ROOT_PASSWORD=admin
#     expose:
#       - 3306
#     networks:
#       - app-network

#   phpmyadmin:
#     build:
#       context: ./docker/phpmyadmin
#     ports:
#       - "8080:80"
#     environment:
#       PMA_HOST: mysql
#     depends_on:
#       - mysql
#     networks:
#       - app-network

# networks:
#   app-network:
#     driver: bridge

# volumes:
#   db_data: {}


version: '3'
services:

  #PHP Service
  php:
    build:
      context: ./docker/php
    container_name: php
    restart: unless-stopped
    tty: true
    environment:
      # - DB_PORT=3306
      # - DB_HOST=mysql
      SERVICE_NAME: php
      SERVICE_TAGS: dev
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
      # - ./docker/php/php-fpm/php-fpm.log:/var/log/php-fpm.log
      - ./docker/php/php.ini:/usr/local/etc/php/conf.d/php.ini
    depends_on:
      - mysql
    networks:
      - app-network

  #Nginx Service
  nginx:
    build:
      context: ./docker/nginx
    container_name: nginx
    restart: unless-stopped
    tty: true
    ports:
      - "8000:80"
      # - "443:443"
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/nginx.conf
      - ./docker/nginx/nginx_log:/var/log/nginx
      # - ./docker/phpmyadmin/phpmyadmin.conf:/etc/nginx/conf.d/phpmyadmin.conf:ro
      # - phpmyadmin_data:/var/www/html/:ro
    depends_on:
      - php
      - mysql
    networks:
      - app-network

  #MySQL Service
  mysql:
    build:
      context: ./docker/mysql
    container_name: mysql
    restart: unless-stopped
    command: --default-authentication-plugin=mysql_native_password
    # tty: true
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: social_media
      MYSQL_ROOT_PASSWORD: null
      MYSQL_ALLOW_EMPTY_PASSWORD: "true"  # Allow empty password
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - db_data:/var/lib/mysql
      - ./docker/mysql/my.cnf:/etc/mysql/my.cnf
    expose:
      - 3306
    networks:
      - app-network

  # phpmyadmin Service
  phpmyadmin:
    build:
      context: ./docker/phpmyadmin
    restart: unless-stopped
    ports:
      - "8081:80"
    environment:
      MYSQL_ROOT_PASSWORD: null
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    # volumes:
    #   - phpmyadmin_data:/var/www/html/
    depends_on:
      - mysql
    links:
      - mysql
    networks:
      - app-network

#Docker Networks
networks:
  app-network:
    driver: bridge

volumes:
  db_data: {}
  # phpmyadmin_data: {}